package(default_visibility = [
    "//visibility:public",
])

exports_files([
    "Launch.storyboard",
    "Main.storyboard",
])

filegroup(
    name = "PhoneAppIcon.xcassets",
    srcs = glob(["PhoneAppIcon.xcassets/**"]),
)
